/**
 * Metadatos de presentación del catálogo (datos puros, sin lógica de simulación):
 * nombres, grupos, descripciones y cómo mostrar cada atributo visible u oculto.
 */
import type { AssetClassId } from './types';

export interface ClassMeta {
  id: AssetClassId | 'stock' | 'bond';
  name: string;
  group:
    | 'Mercados'
    | 'Derivados'
    | 'Inmuebles y activos reales'
    | 'Mercados privados'
    | 'Alternativos'
    | 'Ahorro y previsión';
  glyph: string;
  description: string;
  risk: 1 | 2 | 3 | 4 | 5;
}

export const CLASS_META: readonly ClassMeta[] = [
  {
    id: 'stock',
    name: 'Acciones',
    group: 'Mercados',
    glyph: '◆',
    description: 'Empresas cotizadas en seis países.',
    risk: 4,
  },
  {
    id: 'bond',
    name: 'Bonos',
    group: 'Mercados',
    glyph: '▤',
    description: 'Deuda pública y corporativa con cupón.',
    risk: 2,
  },
  {
    id: 'etf',
    name: 'ETF',
    group: 'Mercados',
    glyph: '≋',
    description:
      'Índices, sectores, temáticos, bonos, materias primas y apalancados. Se liquidan al valor liquidativo de las 18:00.',
    risk: 3,
  },
  {
    id: 'fund',
    name: 'Fondos de gestión activa',
    group: 'Mercados',
    glyph: '◎',
    description: 'Un gestor intenta batir al mercado… cobrando por ello.',
    risk: 3,
  },
  {
    id: 'crypto',
    name: 'Criptoactivos',
    group: 'Mercados',
    glyph: '₿',
    description:
      'Cientos de tokens: majors, DeFi, memecoins, stablecoins. Euforia, pánico y estafas.',
    risk: 5,
  },
  {
    id: 'commodity',
    name: 'Materias primas',
    group: 'Mercados',
    glyph: '⛁',
    description: 'Certificados y metal físico: oro, petróleo, cobre, café, trigo, agua…',
    risk: 4,
  },
  {
    id: 'forex',
    name: 'Divisas',
    group: 'Mercados',
    glyph: '¤',
    description: 'Cuentas y depósitos en moneda extranjera.',
    risk: 3,
  },
  {
    id: 'option',
    name: 'Opciones',
    group: 'Derivados',
    glyph: 'Ω',
    description: 'Calls y puts sobre acciones y el Áureo 20. Pérdida limitada a la prima.',
    risk: 5,
  },
  {
    id: 'future',
    name: 'Futuros',
    group: 'Derivados',
    glyph: '⇥',
    description: 'Materias primas, índices y divisas con margen. Liquidación diaria.',
    risk: 5,
  },
  {
    id: 'cfd',
    name: 'CFD y forex apalancado',
    group: 'Derivados',
    glyph: '⇄',
    description: 'Largos y cortos sobre acciones, índices y cruces de divisas con apalancamiento.',
    risk: 5,
  },
  {
    id: 'realestate',
    name: 'Inmuebles',
    group: 'Inmuebles y activos reales',
    glyph: '⌂',
    description:
      'Pisos, locales, oficinas, naves, terrenos y edificios en los diez barrios de Puerto Valmera.',
    risk: 3,
  },
  {
    id: 'distressed',
    name: 'Embargos y liquidaciones',
    group: 'Inmuebles y activos reales',
    glyph: '⚖',
    description: 'Gangas con sorpresa: inmuebles embargados y lotes de empresas quebradas.',
    risk: 4,
  },
  {
    id: 'farmland',
    name: 'Tierra agrícola',
    group: 'Inmuebles y activos reales',
    glyph: '❦',
    description: 'Olivares, viñedos, cereal, cafetales. Cosechas, clima y subvenciones.',
    risk: 3,
  },
  {
    id: 'energy',
    name: 'Energía',
    group: 'Inmuebles y activos reales',
    glyph: 'ϟ',
    description: 'Participaciones en parques solares, eólicos, baterías y pozos.',
    risk: 3,
  },
  {
    id: 'business',
    name: 'Negocios locales',
    group: 'Mercados privados',
    glyph: '☕',
    description: 'Hazte socio capitalista de cafeterías, talleres, clínicas o gimnasios.',
    risk: 4,
  },
  {
    id: 'franchise',
    name: 'Franquicias',
    group: 'Mercados privados',
    glyph: '✦',
    description: 'Unidades de cadenas conocidas gestionadas por un operador.',
    risk: 3,
  },
  {
    id: 'startup',
    name: 'Startups',
    group: 'Mercados privados',
    glyph: '▲',
    description: 'Rondas de financiación desde pre-semilla a Serie C. Casi todas fracasan.',
    risk: 5,
  },
  {
    id: 'collectible',
    name: 'Coleccionismo',
    group: 'Alternativos',
    glyph: '❖',
    description:
      'Arte, coches clásicos, relojes, vino, cómics, cartas, zapatillas, antigüedades y NFT.',
    risk: 4,
  },
  {
    id: 'entertainment',
    name: 'Cine, música y deporte',
    group: 'Alternativos',
    glyph: '♫',
    description: 'Películas, discos, videojuegos, giras, derechos de deportistas y clubes.',
    risk: 5,
  },
  {
    id: 'p2p',
    name: 'Préstamos P2P',
    group: 'Alternativos',
    glyph: '⇆',
    description: 'Presta a particulares, pymes y microemprendedores desde 25 ₳.',
    risk: 3,
  },
  {
    id: 'pension',
    name: 'Planes de pensiones',
    group: 'Ahorro y previsión',
    glyph: '⌛',
    description: 'Desgravan, pero el dinero queda bloqueado.',
    risk: 2,
  },
  {
    id: 'insurance',
    name: 'Seguros y rentas',
    group: 'Ahorro y previsión',
    glyph: '☂',
    description: 'Seguros de ahorro garantizado, rentas temporales y bonos catástrofe.',
    risk: 2,
  },
  {
    id: 'philanthropy',
    name: 'Filantropía',
    group: 'Ahorro y previsión',
    glyph: '♥',
    description: 'Donaciones con deducción fiscal y reputación.',
    risk: 1,
  },
];

export const LIQUIDITY_LABEL: Record<string, string> = {
  instant: 'Líquido',
  auction: 'Subasta semanal',
  listing: 'Venta en semanas',
  secondary: 'Mercado secundario con descuento',
  none: 'No se puede vender',
};

export type Fmt =
  'pct' | 'money' | 'num' | 'int' | 'text' | 'bool' | 'score' | 'ratio' | 'year' | 'date' | 'days';

/** Atributos visibles: etiqueta y formato. Los que no aparecen aquí no se muestran. */
export const ATTR_LABELS: Record<string, { label: string; fmt: Fmt }> = {
  ter: { label: 'Gastos anuales (TER)', fmt: 'pct' },
  policy: { label: 'Política de dividendos', fmt: 'text' },
  sector: { label: 'Sector', fmt: 'text' },
  theme: { label: 'Temática', fmt: 'text' },
  currency: { label: 'Divisa', fmt: 'text' },
  duration: { label: 'Duración', fmt: 'num' },
  commodity: { label: 'Materia prima', fmt: 'text' },
  leverage: { label: 'Apalancamiento diario', fmt: 'ratio' },
  stars: { label: 'Estrellas Atalaya (pasado)', fmt: 'int' },
  strategy: { label: 'Estrategia', fmt: 'text' },
  manager: { label: 'Gestora', fmt: 'text' },
  guaranteed: { label: 'Interés garantizado', fmt: 'pct' },
  years: { label: 'Plazo (años)', fmt: 'int' },
  monthly: { label: 'Renta mensual por unidad', fmt: 'money' },
  insurer: { label: 'Aseguradora', fmt: 'text' },
  premium: { label: 'Prima anual', fmt: 'pct' },
  minimum: { label: 'Inversión mínima', fmt: 'money' },
  ticker: { label: 'Ticker', fmt: 'text' },
  staking: { label: 'Rendimiento por staking', fmt: 'pct' },
  launched: { label: 'Estado', fmt: 'text' },
  holders: { label: 'Tenedores', fmt: 'int' },
  marketCapBn: { label: 'Capitalización (mil M 𝔇)', fmt: 'num' },
  unit: { label: 'Unidad', fmt: 'text' },
  storage: { label: 'Custodia y seguro anual', fmt: 'pct' },
  months: { label: 'Plazo (meses)', fmt: 'int' },
  underlyingName: { label: 'Subyacente', fmt: 'text' },
  type: { label: 'Tipo', fmt: 'text' },
  strike: { label: 'Precio de ejercicio', fmt: 'num' },
  expiry: { label: 'Vencimiento', fmt: 'date' },
  multiplier: { label: 'Multiplicador', fmt: 'int' },
  premiumShare: { label: 'Prima por título', fmt: 'num' },
  spot: { label: 'Precio del subyacente', fmt: 'num' },
  iv: { label: 'Volatilidad implícita', fmt: 'pct' },
  marginPct: { label: 'Garantía exigida', fmt: 'pct' },
  financing: { label: 'Financiación anual (+ tipo oficial)', fmt: 'pct' },
  roll: { label: 'Coste mensual de renovación', fmt: 'pct' },
  m2: { label: 'Superficie (m²)', fmt: 'int' },
  condition: { label: 'Estado', fmt: 'text' },
  rooms: { label: 'Habitaciones', fmt: 'int' },
  district: { label: 'Barrio', fmt: 'text' },
  rentMonthly: { label: 'Alquiler de mercado / mes', fmt: 'money' },
  rented: { label: 'Alquilado actualmente', fmt: 'bool' },
  appraisal: { label: 'Tasación', fmt: 'money' },
  discount: { label: 'Descuento sobre tasación', fmt: 'pct' },
  inventory: { label: 'Inventario', fmt: 'text' },
  business: { label: 'Negocio', fmt: 'text' },
  owner: { label: 'Dueño', fmt: 'text' },
  stake: { label: 'Participación', fmt: 'pct' },
  claimedProfit: { label: 'Beneficio anual declarado (tu parte)', fmt: 'money' },
  multiple: { label: 'Múltiplo pagado', fmt: 'ratio' },
  yearsOpen: { label: 'Años abierto', fmt: 'int' },
  employees: { label: 'Empleados', fmt: 'int' },
  brand: { label: 'Marca', fmt: 'text' },
  royalty: { label: 'Royalty sobre ventas', fmt: 'pct' },
  fee: { label: 'Canon de entrada', fmt: 'money' },
  expectedProfit: { label: 'Beneficio anual esperado', fmt: 'money' },
  operator: { label: 'Operador', fmt: 'text' },
  company: { label: 'Startup', fmt: 'text' },
  stage: { label: 'Fase', fmt: 'text' },
  founders: { label: 'Fundadores', fmt: 'text' },
  valuation: { label: 'Valoración actual', fmt: 'money' },
  ticket: { label: 'Ticket mínimo', fmt: 'money' },
  roundCloses: { label: 'La ronda cierra', fmt: 'date' },
  growth: { label: 'Crecimiento declarado', fmt: 'text' },
  crop: { label: 'Cultivo', fmt: 'text' },
  ha: { label: 'Hectáreas', fmt: 'int' },
  irrigated: { label: 'Regadío', fmt: 'bool' },
  harvestMonth: { label: 'Mes de cosecha', fmt: 'int' },
  cooperative: { label: 'Cooperativa', fmt: 'text' },
  place: { label: 'Ubicación', fmt: 'text' },
  capex: { label: 'Inversión total del proyecto', fmt: 'money' },
  mw: { label: 'Potencia (MW)', fmt: 'num' },
  expectedYield: { label: 'Rentabilidad prevista', fmt: 'pct' },
  artist: { label: 'Artista', fmt: 'text' },
  km: { label: 'Kilómetros', fmt: 'int' },
  papers: { label: 'Documentación', fmt: 'text' },
  vintage: { label: 'Añada', fmt: 'year' },
  provenance: { label: 'Procedencia', fmt: 'text' },
  fake: { label: 'Falsificación confirmada', fmt: 'bool' },
  athlete: { label: 'Deportista', fmt: 'text' },
  sport: { label: 'Deporte', fmt: 'text' },
  club: { label: 'Club', fmt: 'text' },
  league: { label: 'Categoría', fmt: 'text' },
  release: { label: 'Estreno previsto', fmt: 'date' },
  budget: { label: 'Presupuesto', fmt: 'money' },
  director: { label: 'Dirección', fmt: 'text' },
  rating: { label: 'Calificación', fmt: 'text' },
  rate: { label: 'Interés anual', fmt: 'pct' },
  term: { label: 'Plazo (meses)', fmt: 'int' },
  amount: { label: 'Importe del préstamo', fmt: 'money' },
  platform: { label: 'Plataforma', fmt: 'text' },
  monthsLeft: { label: 'Meses pendientes', fmt: 'int' },
  faction: { label: 'Reputación ante', fmt: 'text' },
};

/** Información oculta: qué se descubre investigando. */
export const HIDDEN_LABELS: Record<string, { label: string; fmt: Fmt; good: 'high' | 'low' }> = {
  alpha: { label: 'Habilidad real del gestor (alfa anual)', fmt: 'pct', good: 'high' },
  decay: { label: 'Erosión anual por volatilidad', fmt: 'pct', good: 'low' },
  catProb: { label: 'Probabilidad anual de catástrofe', fmt: 'pct', good: 'low' },
  legit: { label: 'Proyecto legítimo', fmt: 'bool', good: 'high' },
  rugRisk: { label: 'Riesgo mensual de estafa', fmt: 'pct', good: 'low' },
  depegRisk: { label: 'Riesgo de perder la paridad', fmt: 'pct', good: 'low' },
  defects: { label: 'Reparaciones ocultas (sobre el precio)', fmt: 'pct', good: 'low' },
  tenantRisk: { label: 'Riesgo de impago del inquilino', fmt: 'score', good: 'low' },
  trend: { label: 'Tendencia real del barrio (anual)', fmt: 'pct', good: 'high' },
  squatters: { label: 'Ocupado ilegalmente', fmt: 'bool', good: 'low' },
  liens: { label: 'Cargas pendientes (sobre tasación)', fmt: 'pct', good: 'low' },
  licenceRisk: { label: 'Riesgo mensual de perder la licencia turística', fmt: 'pct', good: 'low' },
  multiple: { label: 'Valor de reventa sobre el precio', fmt: 'ratio', good: 'high' },
  trueRatio: { label: 'Beneficio real frente al declarado', fmt: 'ratio', good: 'high' },
  honesty: { label: 'Honradez del socio', fmt: 'score', good: 'high' },
  failRisk: { label: 'Riesgo anual de cierre', fmt: 'pct', good: 'low' },
  quality: { label: 'Calidad del equipo y del negocio', fmt: 'score', good: 'high' },
  integrity: { label: 'Integridad de los fundadores', fmt: 'score', good: 'high' },
  soil: { label: 'Productividad del suelo', fmt: 'ratio', good: 'high' },
  waterSecurity: { label: 'Seguridad del agua', fmt: 'score', good: 'high' },
  capacity: { label: 'Producción real frente a la prevista', fmt: 'ratio', good: 'high' },
  regulation: { label: 'Riesgo regulatorio mensual', fmt: 'pct', good: 'low' },
  authentic: { label: 'Pieza auténtica', fmt: 'bool', good: 'high' },
  peak: { label: 'Año óptimo de consumo', fmt: 'year', good: 'high' },
  hit: { label: 'Potencial comercial', fmt: 'score', good: 'high' },
  overrun: { label: 'Riesgo mensual de sobrecostes', fmt: 'pct', good: 'low' },
  talent: { label: 'Talento / momento de forma', fmt: 'score', good: 'high' },
  pd: { label: 'Probabilidad real de impago anual', fmt: 'pct', good: 'low' },
  platformRisk: { label: 'Riesgo de quiebra de la plataforma', fmt: 'pct', good: 'low' },
};

export const RESEARCH_LEVELS = [
  'Sin investigar',
  'Consulta rápida',
  'Análisis a fondo',
  'Due diligence completa',
] as const;
